### ISSUE TITLE
lwip_bind Assertion

### ISSUE THREAD

**Issue by hansprove** [quiet/quiet-lwip#1]
Hi,

When trying to run the proxy_server.c I get following error:

Assertion "lwip_bind: invalid address" failed at line 421 in /home/hans/git/quiet-lwip/src/lwip/api/sockets.c

I am running the example without code modification and disocvery_server and client are working fine

I am not familiar with C coding and am not sure how to make the example work, I can provide more information when needed but not quiet sure which info is usefull

**Comment by brian-armstrong** [comment]
Hi!

I think this might have been a portability issue. The proxy client/server is strange in that it has to deal with sockets in the native domain and the lwip domain at the same time, and there are a few places where discrepancies in those systems wouldn't work. I think I've fixed the most likely one, so if you wouldn't mind, pull the latest change and let me know if it happens again.

**Comment by hansprove** [comment]
Works like a charm!
